import { supabaseAdmin } from '@/lib/supabase/admin';
import type {
  BrandRow,
  ConceptRow,
  PillarRow,
  PostRow,
  SnapshotRow,
} from '@/lib/types/db';

export interface AgentContext {
  brand: BrandRow;
  latestSnapshot: SnapshotRow | null;
  topPosts: PostRow[];
  pillars: PillarRow[];
  recentConcepts: ConceptRow[];
}

export const EMPTY_BRAND: BrandRow = {
  id: 1,
  facts: [],
  voice_examples: [],
  palette: null,
  typography: null,
  audience_notes: null,
  status: 'seed',
  updated_at: new Date(0).toISOString(),
};

/** Reads everything the agent is allowed to know. Nothing else reaches it. */
export async function loadAgentContext(topPostLimit = 15): Promise<AgentContext> {
  const db = supabaseAdmin();

  const [{ data: brand }, { data: snapshots }] = await Promise.all([
    db.from('brand').select('*').eq('id', 1).maybeSingle(),
    db.from('snapshots').select('*').order('taken_on', { ascending: false }).limit(1),
  ]);

  const latestSnapshot = (snapshots?.[0] as SnapshotRow | undefined) ?? null;

  const [{ data: posts }, { data: pillars }, { data: concepts }] = await Promise.all([
    latestSnapshot
      ? db
          .from('posts')
          .select('*')
          .eq('snapshot_id', latestSnapshot.id)
          .order('rank', { ascending: true })
          .limit(topPostLimit)
      : Promise.resolve({ data: [] as PostRow[] }),
    db.from('pillars').select('*').order('avg_engagement', { ascending: false }),
    db.from('concepts').select('*').order('created_at', { ascending: false }).limit(12),
  ]);

  return {
    brand: (brand as BrandRow | null) ?? EMPTY_BRAND,
    latestSnapshot,
    topPosts: (posts as PostRow[] | null) ?? [],
    pillars: (pillars as PillarRow[] | null) ?? [],
    recentConcepts: (concepts as ConceptRow[] | null) ?? [],
  };
}

export function daysSince(dateIso: string | null | undefined): number | null {
  if (!dateIso) return null;
  const then = new Date(dateIso).getTime();
  if (Number.isNaN(then)) return null;
  return Math.floor((Date.now() - then) / 86_400_000);
}

function block(tag: string, body: unknown): string {
  return `<${tag}>\n${JSON.stringify(body, null, 2)}\n</${tag}>`;
}

/**
 * Renders the four context blocks named in the system prompt. Posts are trimmed
 * to the fields the agent can actually reason about — captions are truncated so
 * a long export doesn't crowd out the rest of the context.
 */
export function renderContextBlocks(ctx: AgentContext): string {
  const brand = block('brand', {
    status: ctx.brand.status,
    facts: ctx.brand.facts,
    voice_examples: ctx.brand.voice_examples,
    palette: ctx.brand.palette,
    typography: ctx.brand.typography,
    audience_notes: ctx.brand.audience_notes,
  });

  const snapshot = ctx.latestSnapshot
    ? block('latest_snapshot', {
        id: ctx.latestSnapshot.id,
        taken_on: ctx.latestSnapshot.taken_on,
        days_old: daysSince(ctx.latestSnapshot.taken_on),
        stats: ctx.latestSnapshot.stats,
        top_posts: ctx.topPosts.map((p) => ({
          id: p.id,
          account: p.account,
          rank: p.rank,
          engagement: p.engagement,
          likes: p.likes,
          comments: p.comments,
          media_type: p.media_type,
          posted_at: p.posted_at,
          url: p.url,
          caption_excerpt: p.caption ? p.caption.slice(0, 600) : null,
        })),
      })
    : '<latest_snapshot>null — no engagement export has been ingested yet.</latest_snapshot>';

  const pillars =
    ctx.pillars.length > 0
      ? block(
          'pillars',
          ctx.pillars.map((p) => ({
            name_ar: p.name_ar,
            name_en: p.name_en,
            post_count: p.post_count,
            avg_engagement: p.avg_engagement,
            hook_pattern: p.hook_pattern,
          })),
        )
      : '<pillars>[] — pillars are generated by Run Refresh once a snapshot exists.</pillars>';

  const recent =
    ctx.recentConcepts.length > 0
      ? block(
          'recent_concepts',
          ctx.recentConcepts.map((c) => ({
            title: c.title,
            format: c.format,
            hook_ar: c.hook_ar,
            status: c.status,
            grounding: c.grounding,
            account: c.account,
            shipped_engagement: c.shipped_engagement,
          })),
        )
      : '<recent_concepts>[] — nothing generated yet.</recent_concepts>';

  return [brand, snapshot, pillars, recent].join('\n\n');
}
